#!/bin/bash
#
#SBATCH --job-name=gp_surps_rnng
#SBATCH -o logs/JOB_%A_%a.out                # Name of stdout output log file (%j expands to jobID)
#SBATCH -e logs/JOB_%A_%a.err                # Name of stderr output log file (%j expands to jobID)
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=24GB
#SBATCH --gres=gpu:1
#SBATCH --array 2398-2402

singularity exec --nv \
	    --overlay /scratch/wpt2011/my_pytorch.ext3:ro \
	    /scratch/work/public/singularity/cuda11.6.124-cudnn8.4.0.27-devel-ubuntu20.04.4.sif\
	    /bin/bash -c "source /ext3/env.sh;
        python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 1 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 1 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 2 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_2_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_2_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 2 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_2_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_2_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 3 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_3_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_3_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 3 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_3_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_3_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 4 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_4_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_4_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 4 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_4_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_4_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 5 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_5_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_5_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 5 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_5_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_5_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 10 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_10_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_10_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 10 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_10_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_10_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 25 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_25_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_25_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 25 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_25_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_25_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 50 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_50_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_50_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 50 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_50_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_50_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 100 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_100_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_100_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 100 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_100_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_100_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 250 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_250_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_250_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 250 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_250_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_250_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 500 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_500_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_500_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 500 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_500_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_500_0_ambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_unambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 1000 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1000_0_unambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1000_0_unambig.parsed;
		python beam_search.py --dump_beam --sort_by_preword_probs --test_file ../../data/sap_stimuli/sap_gp_ambig_raw.txt --model_file ./models/rnng_bllip_inorder_512_2_${SLURM_ARRAY_TASK_ID}.pt --batch_size 1 --beam_size 1000 --word_beam_size 1000 --shift_size 0 --block_size 1000 --gpu 0 --lm_output_file ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1000_0_ambig.surps > ../../data/model_outputs/rnng_topdown/${SLURM_ARRAY_TASK_ID}_1000_1000_0_ambig.parsed;"
